# Generated by Django 5.2.7 on 2025-10-17 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_seoresult_delete_seoreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('audit_data', models.JSONField()),
                ('change_detected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('webhook_url', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('last_score', models.IntegerField(blank=True, null=True)),
                ('last_audit_data', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SEOResult',
        ),
        migrations.AddField(
            model_name='seoauditlog',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='myapp.website'),
        ),
    ]
