# Generated by Django 5.2.7 on 2025-10-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_seoauditlog_website_delete_seoresult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='email',
        ),
        migrations.AddField(
            model_name='website',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
